In [1]:
import json
import sqlite3

conn = sqlite3.connect('rosterdb.sqlite')
cur = conn.cursor()

# Do some setup
cur.executescript('''
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Course;

CREATE TABLE User (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name   TEXT UNIQUE
);

CREATE TABLE Course (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    title  TEXT UNIQUE
);

CREATE TABLE Member (
    user_id     INTEGER,
    course_id   INTEGER,
    role        INTEGER,
    PRIMARY KEY (user_id, course_id)
)
''')

fname = input('Enter file name: ')
if len(fname) < 1:
    fname = 'roster_data.json'

# [
#   [ "Charley", "si110", 1 ],
#   [ "Mea", "si110", 0 ],

str_data = open(fname).read()
json_data = json.loads(str_data)

for entry in json_data:

    name = entry[0];
    title = entry[1];
    role = entry[2];

    print((name, title, role))

    cur.execute('''INSERT OR IGNORE INTO User (name)
        VALUES ( ? )''', ( name, ) )
    cur.execute('SELECT id FROM User WHERE name = ? ', (name, ))
    user_id = cur.fetchone()[0]

    cur.execute('''INSERT OR IGNORE INTO Course (title)
        VALUES ( ? )''', ( title, ) )
    cur.execute('SELECT id FROM Course WHERE title = ? ', (title, ))
    course_id = cur.fetchone()[0]

    cur.execute('''INSERT OR REPLACE INTO Member
        (user_id, course_id,role) VALUES ( ?, ? ,? )''',
        ( user_id, course_id, role ) )

    conn.commit()

Enter file name:  roster_data.json

('Shauntel', 'si110', 1)
('Deagan', 'si110', 0)
('Kemi', 'si110', 0)
('Jordan', 'si110', 0)
('Evelyne', 'si110', 0)
('Tasneem', 'si110', 0)
('Eilidh', 'si110', 0)
('Dela', 'si110', 0)
('Derrin', 'si110', 0)
('Karishma', 'si110', 0)
('Willow', 'si110', 0)
('Konar', 'si110', 0)
('Abia', 'si110', 0)
('Theo', 'si110', 0)
('Dylan', 'si110', 0)
('Baley', 'si110', 0)
('Nicky', 'si110', 0)
('Kirie', 'si106', 1)
('Seriah', 'si106', 0)
('Reaiah', 'si106', 0)
('Skyler', 'si106', 0)
('Solomon', 'si106', 0)
('Olaoluwapolorimi', 'si106', 0)
('Fenn', 'si106', 0)
('Idris', 'si106', 0)
('Charlotte', 'si106', 0)
('Manwen', 'si106', 0)
('Caiden', 'si106', 0)
('Dhyia', 'si106', 0)
('Harlie', 'si106', 0)
('Mantej', 'si106', 0)
('Avani', 'si106', 0)
('Hately', 'si106', 0)
('Makenzie', 'si106', 0)
('Riley', 'si106', 0)
('Oluwateniolami', 'si106', 0)
('Toluwalase', 'si106', 0)
('Aisha', 'si106', 0)
('Helia', 'si106', 0)
('Sharlyn', 'si206', 1)
('Nivedita', 'si206', 0)
('Arianna', 'si206', 0)
('Badsha', 'si206', 0)
('Latoya', 'si206', 0)
('Eljay', 'si206', 0)
('Kelsay', 'si206', 0)
('Lileidh', 'si206', 0)
('Kararose', 'si206', 0)
('Murran', 'si206', 0)
('Alycia', 'si206', 0)
('Calder', 'si206', 0)
('Melis', 'si206', 0)
('Nicol', 'si206', 0)
('Alisha', 'si206', 0)
('Cassie', 'si206', 0)
('Damian', 'si206', 0)
('Luci', 'si206', 0)
('Hugh', 'si206', 0)
('Sonneey', 'si206', 0)
('Rhea', 'si206', 0)
('Eni', 'si206', 0)
('Maizy', 'si206', 0)
('Emon', 'si206', 0)
('Keeley', 'si206', 0)
('Kienan', 'si206', 0)
('Verity', 'si206', 0)
('Caiolea', 'si206', 0)
('Phinehas', 'si206', 0)
('Saifaddine', 'si206', 0)
('Maksim', 'si206', 0)
('Teejay', 'si206', 0)
('Ewen', 'si206', 0)
('Akan', 'si206', 0)
('Iona', 'si206', 0)
('Imogen', 'si206', 0)
('Dilly', 'si206', 0)
('Oluwadamilare', 'si206', 0)
('Lorin', 'si206', 0)
('Kaitlyn', 'si206', 0)
('Caoimhe', 'si206', 0)
('Albert', 'si206', 0)
('Shanade', 'si206', 0)
('Noah', 'si206', 0)
('Graeme', 'si301', 1)
('Anousha', 'si301', 0)
('Oluwalayomi', 'si301', 0)
('Kaden', 'si301', 0)
('Elize', 'si301', 0)
('Remigiusz', 'si301', 0)
('Meftah', 'si301', 0)
('Abdallah', 'si301', 0)
('Asra', 'si301', 0)
('Marriam', 'si301', 0)
('Laoise', 'si301', 0)
('Milli', 'si301', 0)
('Samanta', 'si301', 0)
('Turki', 'si301', 0)
('Jaskaran', 'si301', 0)
('Kia', 'si301', 0)
('Bethel', 'si301', 0)
('Ian', 'si301', 0)
('Lokesh', 'si301', 0)
('Crawford', 'si301', 0)
('Tye', 'si301', 0)
('Mahan', 'si310', 1)
('Kelso', 'si310', 0)
('Kyrran', 'si310', 0)
('Cale', 'si310', 0)
('Amie', 'si310', 0)
('Ariah', 'si310', 0)
('Coray', 'si310', 0)
('Shanzay', 'si310', 0)
('Kaison', 'si310', 0)
('Jaime', 'si310', 0)
('Jeswin', 'si310', 0)
('Adegbola', 'si310', 0)
('Aeva', 'si310', 0)
('Antoni', 'si310', 0)
('Tamara', 'si310', 0)
('Keith', 'si310', 0)
('Tymon', 'si310', 0)
('Jameel', 'si310', 0)
('Rajwinder', 'si310', 0)
('Dafydd', 'si310', 0)
('Murren', 'si310', 0)
('Samiha', 'si310', 0)
('Musa', 'si310', 0)
('Eren', 'si310', 0)
('Jiao', 'si310', 0)
('Omri', 'si310', 0)
('Cherry', 'si310', 0)
('Angelic', 'si310', 0)
('Kinsey', 'si310', 0)
('Rosalind', 'si310', 0)
('Harriet', 'si310', 0)
('Nikolina', 'si310', 0)
('Beau', 'si310', 0)
('Mobeen', 'si310', 0)
('Hala', 'si310', 0)
('Yana', 'si310', 0)
('Amez', 'si310', 0)
('Ruben', 'si310', 0)
('Leya', 'si310', 0)
('Bobbi', 'si310', 0)
('Ayyub', 'si310', 0)
('Daniels', 'si310', 0)
('Adrien', 'si310', 0)
('Chris', 'si310', 0)
('Cillian', 'si310', 0)
('May', 'si310', 0)
('Adam', 'si310', 0)
('Kaydn', 'si334', 1)
('Uilleam', 'si334', 0)
('Rheo', 'si334', 0)
('Alessandro', 'si334', 0)
('Kiefer', 'si334', 0)
('Shalamar', 'si334', 0)
('Sum', 'si334', 0)
('Sandy', 'si334', 0)
('Ayla', 'si334', 0)
('Isabelle', 'si334', 0)
('Aiyanna', 'si334', 0)
('Mara', 'si334', 0)
('Logan', 'si334', 0)
('Teghan', 'si334', 0)
('Malika', 'si334', 0)
('Amaia', 'si334', 0)
('Wei', 'si334', 0)
('Rihan', 'si334', 0)
('Inemesit', 'si334', 0)
('Keryn', 'si334', 0)
('Miller', 'si334', 0)
('Danielle', 'si334', 0)
('Lilia', 'si334', 0)
('Carrich', 'si334', 0)
('Nicky', 'si334', 0)
('Hendri', 'si334', 0)
('Symon', 'si363', 1)
('Daniyal', 'si363', 0)
('Piotr', 'si363', 0)
('Becky', 'si363', 0)
('Lauren', 'si363', 0)
('Reiss', 'si363', 0)
('Asrar', 'si363', 0)
('Mazin', 'si363', 0)
('Majid', 'si363', 0)
('Flynn', 'si363', 0)
('Sianna', 'si363', 0)
('Chimsom', 'si363', 0)
('Reuben', 'si363', 0)
('Elyssa', 'si363', 0)
('Radmiras', 'si363', 0)
('Tylor', 'si363', 0)
('Sudais', 'si363', 0)
('Elliana', 'si363', 0)
('Uzma', 'si363', 0)
('Sehar', 'si363', 0)
('Michat', 'si363', 0)
('Ilona', 'si363', 0)
('Derryne', 'si363', 0)
('Leia', 'si363', 0)
('Gigha', 'si363', 0)
('Zi', 'si363', 0)
('Phillipa', 'si363', 0)
('Leighton', 'si363', 0)
('Shayaan', 'si363', 0)
('Leona', 'si363', 0)
('Keane', 'si363', 0)
('Niobe', 'si363', 0)
('Lylah', 'si363', 0)
('Latoya', 'si363', 0)
('Caceylee', 'si363', 0)
('Allen', 'si363', 0)
('Luci', 'si363', 0)
('Cadie', 'si364', 1)
('Arissa', 'si364', 0)
('Rajan', 'si364', 0)
('Jad', 'si364', 0)
('Iseabel', 'si364', 0)
('Kajetan', 'si364', 0)
('Jae', 'si364', 0)
('Abiya', 'si364', 0)
('Korey', 'si364', 0)
('Annastacia', 'si364', 0)
('Darla', 'si364', 0)
('Daniyal', 'si364', 0)
('Ceilidh', 'si364', 0)
('Zak', 'si364', 0)
('Larissa', 'si364', 0)
('Airen', 'si364', 0)
('Zachariya', 'si364', 0)
('Sweyn', 'si364', 0)
('Naz', 'si364', 0)
('Hadyn', 'si364', 0)
('Andie', 'si364', 0)
('Meleia', 'si364', 0)
('Aizah', 'si364', 0)
('Annaliesse', 'si364', 0)
('Anna', 'si364', 0)
('Kellan', 'si364', 0)
('Ayman', 'si364', 0)
('Harris', 'si364', 0)
('Darcy', 'si422', 1)
('Aeron', 'si422', 0)
('Zain', 'si422', 0)
('Jewel', 'si422', 0)
('Leonardo', 'si422', 0)
('Ama', 'si422', 0)
('Jing', 'si422', 0)
('Max', 'si422', 0)
('Virginie', 'si422', 0)
('Hadiyah', 'si422', 0)
('Dawn', 'si422', 0)
('Jenni', 'si422', 0)
('Aahana', 'si422', 0)
('May', 'si422', 0)
('Harman', 'si422', 0)
('Hassanali', 'si422', 0)
('Arabella', 'si422', 0)
('Oluwademilade', 'si430', 1)
('Manmohan', 'si430', 0)
('Aaryan', 'si430', 0)
('Kaleigh', 'si430', 0)
('Lincoln', 'si430', 0)
('Salman', 'si430', 0)
('Kamila', 'si430', 0)
('Divinewill', 'si430', 0)
('Marrwa', 'si430', 0)
('Zeph', 'si430', 0)
('Motade', 'si430', 0)
('Christina', 'si430', 0)
('Yasin', 'si430', 0)
('Barath', 'si430', 0)
('Irem', 'si430', 0)
('Kiran', 'si430', 0)
('Rhy', 'si430', 0)
('Bryony', 'si430', 0)